# Generated by Django 4.2.1 on 2023-06-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="institution",
            name="webpage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="institution",
            name="location",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
