# Generated by Django 4.2.1 on 2023-06-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0002_institution_logo_institution_webpage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="degree",
            name="semesters",
        ),
        migrations.RemoveField(
            model_name="degree",
            name="years",
        ),
        migrations.AddField(
            model_name="degree",
            name="abbrev",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="degree",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
