# Generated by Django 4.2.1 on 2023-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0003_remove_degree_semesters_remove_degree_years_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="smprofile_url",
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="profile_url",
            field=models.URLField(blank=True, max_length=30),
        ),
    ]
