# Generated by Django 4.2.1 on 2023-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0004_teacher_smprofile_url_alter_teacher_profile_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teaches", to="myportfolio.teacher"
            ),
        ),
    ]
