# Generated by Django 4.2.1 on 2023-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0006_alter_class_semester_alter_class_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="semester",
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name="class",
            name="year",
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
