# Generated by Django 4.2.1 on 2023-06-14 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myportfolio", "0007_alter_class_semester_alter_class_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="degree",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
